### ISSUE TITLE
Initial clone state doesn't run under Qt Creator

### ISSUE THREAD

**Issue by jabowery** [pgliaskovitis/confabulation-engine#1]
Here is my install procedure for confabulation-engine under Ubuntu:

```
$ sudo apt install libsparsehash-dev qtcreator qt5-default
$ git clone
$ git clone git@github.com:pgliaskovitis/confabulation-engine.git
```

I was then able use the file manager to double click on `confabulation-engine/ConfabulationEngine.pro` to bring up the IDE.  I then clicked on the "configure project" button (or some such) and was then able to build (with numerous warnings but no errors) and then run.

However, after a terminal opened up and issued a lot of warnings, the run failed with:

```Failed to initialize at initial excitation level: 1```

As per the README instruction that execution must be in the same directory as the executable, I changed the run working directory to:

```confabulation-engine/text_data```

However, this also failed.

Running it with `gdb` in a terminal to see where the warnings were coming from I found this line commented in to be the source:

```test1->TestTwoLevelMultiConfabulation("text_data/ascii_symbols.txt", "text_data/sample_master_selection.txt", *allOriginalFeeds);```

As the paths already contained `text_data`, I removed it from the run working directory in the project configuration and ran it from there again, but this failed as well.

**Comment by jabowery** [comment]
The Qt Creator run worked after I commented out that line of source and commented in the prior line.  The file `text_data/sample_master_selection.txt` was not in my clone.

**Comment by pgliaskovitis** [comment]
Yes, my mistake, I had committed code pointing to my own text selection
file. Thanks for pointing it out.

Did you manage to compile it with SparseHash? That was a bit tricky for me.

**Comment by jabowery** [comment]
Since the README said SparseHash was required and didn't say it was optional, I presumed it was compiled with it by default.  I didn't have trouble compiling.  At least there were no compile errors or link errors reported by Qt Creator).

BTW: It's now doing two level multiconfabulation with these as the first 4 results:

```Ultimately, his quest was one of { the } { folk } { and } { the } { and } { the } { which }
Fortunately, there will always exist { the } { end } { of } { his } { and } { is } { the }
As it turns out, luck favors the { little } { of } { the } { and } { of } { the } { the }
The hooded men were chanting beneath the { the } { the } { and } { the } { one } { in } { the }```

The last one, in particular, gives the appearance of a bug in the cogency calculation if 'the' is the most cogent next word.

Are all of those words in `{}` supposed to be the most cogent words for those places as determined by multiconfabulation's "swirling" "consensus" between modules (to use RNH's descriptive words)?

**Comment by pgliaskovitis** [comment]
In general, you need much more data than the 10 text files that are
committed on github to get something meaningful. You should place more
clear text files under text_data folder and then add their names into the
sample_master_reduced.txt like the others.

I have only managed to try it with ~400 MB of data on a home computer (32
GB memory), which is still too low. I will try going on leased machines on
the cloud soon.

Some of the most meaningful results I have gotten, even with so few data
are (on right hand side):

Hosts of archers stood ready along the | bridge road that led to the sea
Enlightenment goes well with a | bucket of cold water
The cave was too high up for him to | lift the burden of his body
A dark winter was eating through the | plains of the north

I can post these at the Readme. They are cherry picked ofc, but not so bad
in my opinion.

**Comment by jabowery** [comment]
That would be a good idea.  I'd nowhere near the capacity to try this out except at the "does it run at all" level of testing.
